-- =============================================================================
-- 025_recipe_seed.sql
-- 25 halal seed recipes attributed to the platform owner account.
-- Safe to re-run: skips if profile does not exist.
-- =============================================================================

DO $$
DECLARE
  v_uid UUID := '0625de77-8d43-4bf3-8749-24d8a17e4229';
BEGIN
  IF NOT EXISTS (SELECT 1 FROM profiles WHERE id = v_uid) THEN
    RAISE NOTICE 'Profile % not found — skipping recipe seed.', v_uid;
    RETURN;
  END IF;

  INSERT INTO recipes
    (user_id, title, description, instructions, ingredients,
     cuisine, difficulty, cook_time_mins, servings,
     image_url, is_published, is_halal_verified, tags)
  VALUES

  -- ── 1. Chicken Biryani ────────────────────────────────────────────────────
  (v_uid,
   'Chicken Biryani',
   'Fragrant, layered rice cooked with tender marinated chicken, whole spices, and golden caramelised onions. A timeless South Asian showstopper.',
   '[{"step":1,"text":"Marinate chicken in yogurt, biryani masala, ginger-garlic paste and salt for at least 2 hours."},
     {"step":2,"text":"Parboil basmati rice with whole spices (bay leaf, cardamom, cinnamon) until 70% cooked. Drain and set aside."},
     {"step":3,"text":"In a heavy pot, heat ghee and fry sliced onions until deep golden. Reserve half for garnish."},
     {"step":4,"text":"Add marinated chicken to the pot and cook on high heat for 5 minutes to seal the juices."},
     {"step":5,"text":"Layer the parboiled rice over the chicken. Scatter saffron milk, fried onions, mint and coriander on top."},
     {"step":6,"text":"Seal the pot with foil then the lid. Cook on low heat (dum) for 25 minutes. Rest 10 minutes before serving."}]'::jsonb,
   '[{"name":"chicken thighs (bone-in)","amount":"1","unit":"kg"},
     {"name":"basmati rice","amount":"500","unit":"g"},
     {"name":"full-fat yogurt","amount":"200","unit":"ml"},
     {"name":"biryani masala","amount":"3","unit":"tbsp"},
     {"name":"ghee","amount":"4","unit":"tbsp"},
     {"name":"onions (sliced)","amount":"3","unit":"large"},
     {"name":"saffron","amount":"1","unit":"pinch"},
     {"name":"fresh mint leaves","amount":"1","unit":"handful"}]'::jsonb,
   'South Asian', 'medium', 90, 5,
   '/images/Recipes/chicken-biryani.jpg',
   true, true, ARRAY['rice','chicken','dum','spiced']),

  -- ── 2. Butter Chicken ────────────────────────────────────────────────────
  (v_uid,
   'Butter Chicken',
   'Silky, mildly spiced tomato-cream curry with tender grilled chicken. The dish that made Indian food famous worldwide.',
   '[{"step":1,"text":"Mix chicken with yogurt, turmeric, cumin and salt. Grill or pan-fry until charred. Set aside."},
     {"step":2,"text":"Melt butter in a pan. Sauté onion until soft, then add ginger-garlic paste and cook 2 minutes."},
     {"step":3,"text":"Add blended tomatoes, Kashmiri chilli powder and cook on medium heat until oil separates (10–12 min)."},
     {"step":4,"text":"Pour in double cream and honey. Stir to combine and simmer 5 minutes."},
     {"step":5,"text":"Add the grilled chicken pieces. Simmer gently for 10 minutes so they absorb the sauce."},
     {"step":6,"text":"Finish with dried fenugreek leaves (kasuri methi) and a knob of butter. Serve with naan."}]'::jsonb,
   '[{"name":"chicken breast (cubed)","amount":"700","unit":"g"},
     {"name":"unsalted butter","amount":"60","unit":"g"},
     {"name":"double cream","amount":"150","unit":"ml"},
     {"name":"tinned chopped tomatoes","amount":"400","unit":"g"},
     {"name":"onion","amount":"1","unit":"large"},
     {"name":"Kashmiri chilli powder","amount":"1.5","unit":"tsp"},
     {"name":"kasuri methi","amount":"1","unit":"tsp"},
     {"name":"honey","amount":"1","unit":"tsp"}]'::jsonb,
   'South Asian', 'easy', 40, 4,
   '/images/Recipes/butter-chicken.jpg',
   true, true, ARRAY['curry','creamy','mild','chicken']),

  -- ── 3. Lamb Seekh Kebab ──────────────────────────────────────────────────
  (v_uid,
   'Lamb Seekh Kebab',
   'Juicy minced lamb threaded on skewers and grilled over charcoal. Spiced with fresh herbs, green chilli and aromatic garam masala.',
   '[{"step":1,"text":"Combine lamb mince, finely grated onion, green chilli, ginger-garlic paste, cumin, coriander, garam masala, salt and fresh coriander. Mix vigorously for 2 minutes so the mixture becomes sticky."},
     {"step":2,"text":"Wet your hands and press the mixture firmly around flat metal skewers in a sausage shape, about 15 cm long."},
     {"step":3,"text":"Chill on a tray for 30 minutes so they hold their shape."},
     {"step":4,"text":"Grill over high heat (charcoal or griddle) for 10–12 minutes, turning every 2–3 minutes, until cooked through with light char marks."},
     {"step":5,"text":"Serve immediately with mint chutney, sliced onions and lemon wedges."}]'::jsonb,
   '[{"name":"lamb mince (20% fat)","amount":"600","unit":"g"},
     {"name":"onion (grated)","amount":"1","unit":"medium"},
     {"name":"green chilli","amount":"2","unit":""},
     {"name":"ginger-garlic paste","amount":"1.5","unit":"tbsp"},
     {"name":"garam masala","amount":"1","unit":"tsp"},
     {"name":"ground cumin","amount":"1","unit":"tsp"},
     {"name":"fresh coriander (chopped)","amount":"3","unit":"tbsp"},
     {"name":"chaat masala","amount":"0.5","unit":"tsp"}]'::jsonb,
   'South Asian', 'medium', 30, 4,
   '/images/Recipes/lamb-seekh-kebab.jpg',
   true, true, ARRAY['kebab','grilled','lamb','bbq']),

  -- ── 4. Dal Makhani ───────────────────────────────────────────────────────
  (v_uid,
   'Dal Makhani',
   'Slow-cooked black lentils and kidney beans simmered overnight with butter, cream and tomatoes. Rich, indulgent and deeply comforting.',
   '[{"step":1,"text":"Rinse black lentils and kidney beans. Soak in cold water for 8 hours or overnight."},
     {"step":2,"text":"Drain, then pressure-cook with water and salt for 20–25 minutes until very soft."},
     {"step":3,"text":"In a separate pan, melt butter and fry finely chopped onion until golden. Add ginger-garlic paste and cook 2 minutes."},
     {"step":4,"text":"Add tomato passata, chilli powder and cumin. Cook on medium heat until the masala thickens and oil rises (15 min)."},
     {"step":5,"text":"Pour the cooked lentils into the masala. Stir well and simmer on very low heat for 30 minutes, stirring often."},
     {"step":6,"text":"Stir in cream and another knob of butter. Simmer 10 more minutes. Garnish with a swirl of cream."}]'::jsonb,
   '[{"name":"whole black lentils (urad dal)","amount":"250","unit":"g"},
     {"name":"red kidney beans (dried)","amount":"50","unit":"g"},
     {"name":"butter","amount":"60","unit":"g"},
     {"name":"double cream","amount":"100","unit":"ml"},
     {"name":"tomato passata","amount":"200","unit":"ml"},
     {"name":"onion","amount":"1","unit":"medium"},
     {"name":"Kashmiri chilli powder","amount":"1","unit":"tsp"},
     {"name":"ginger-garlic paste","amount":"1","unit":"tbsp"}]'::jsonb,
   'South Asian', 'easy', 90, 4,
   '/images/Recipes/dal-makhani.jpg',
   true, true, ARRAY['lentils','vegetarian','slow-cooked','comfort']),

  -- ── 5. Haleem ────────────────────────────────────────────────────────────
  (v_uid,
   'Haleem',
   'A hearty, slow-cooked stew of broken wheat, barley, lentils and melt-in-the-mouth lamb. A Ramadan and celebratory favourite.',
   '[{"step":1,"text":"Soak broken wheat, barley, chana dal and masoor dal together in water for 4 hours. Drain."},
     {"step":2,"text":"In a heavy pot, heat ghee and fry onion until deep golden. Add lamb, ginger-garlic paste and haleem masala. Cook 10 minutes."},
     {"step":3,"text":"Add 2 litres of water. Bring to boil, then simmer on low heat for 2 hours, skimming foam as needed."},
     {"step":4,"text":"Remove lamb pieces, shred the meat off the bone and return to the pot."},
     {"step":5,"text":"Add the soaked grains to the pot. Cook for another 45 minutes, stirring constantly, until the mixture thickens to a porridge-like consistency."},
     {"step":6,"text":"Use a hand blender to partially blend for texture. Adjust seasoning."},
     {"step":7,"text":"Serve topped with crispy fried onions, fresh ginger julienne, lemon juice and chopped coriander."}]'::jsonb,
   '[{"name":"bone-in lamb (cubed)","amount":"700","unit":"g"},
     {"name":"broken wheat (daliya)","amount":"150","unit":"g"},
     {"name":"barley","amount":"50","unit":"g"},
     {"name":"chana dal","amount":"50","unit":"g"},
     {"name":"masoor dal","amount":"50","unit":"g"},
     {"name":"haleem masala","amount":"3","unit":"tbsp"},
     {"name":"ghee","amount":"4","unit":"tbsp"},
     {"name":"onions","amount":"3","unit":"large"}]'::jsonb,
   'South Asian', 'hard', 180, 6,
   '/images/Recipes/haleem.jpg',
   true, true, ARRAY['lamb','grains','slow-cooked','Ramadan']),

  -- ── 6. Chicken Nihari ────────────────────────────────────────────────────
  (v_uid,
   'Chicken Nihari',
   'A slow-braised, deeply spiced gravy with fall-off-the-bone chicken. Originally a royal breakfast dish, now a beloved weekend treat.',
   '[{"step":1,"text":"Heat ghee in a heavy pot. Add whole spices (bay leaf, black cardamom, cloves) and fry 30 seconds."},
     {"step":2,"text":"Add sliced onion and cook until light golden. Add ginger-garlic paste and nihari masala; stir 2 minutes."},
     {"step":3,"text":"Add chicken pieces and sear on high heat for 5 minutes."},
     {"step":4,"text":"Pour in 600ml water. Bring to a boil, reduce heat and simmer covered for 1 hour."},
     {"step":5,"text":"Mix wheat flour with 4 tbsp cold water to form a slurry. Stir into the curry to thicken the gravy."},
     {"step":6,"text":"Simmer uncovered for 20 more minutes until gravy is glossy and coats the back of a spoon."},
     {"step":7,"text":"Serve with naan, topped with ginger julienne, lemon juice and fresh coriander."}]'::jsonb,
   '[{"name":"chicken (bone-in pieces)","amount":"1","unit":"kg"},
     {"name":"ghee","amount":"4","unit":"tbsp"},
     {"name":"nihari masala","amount":"3","unit":"tbsp"},
     {"name":"onion","amount":"2","unit":"large"},
     {"name":"ginger-garlic paste","amount":"2","unit":"tbsp"},
     {"name":"whole wheat flour","amount":"3","unit":"tbsp"},
     {"name":"fresh ginger (julienne)","amount":"30","unit":"g"},
     {"name":"lemon","amount":"1","unit":""}]'::jsonb,
   'South Asian', 'hard', 100, 4,
   '/images/Recipes/chicken-nihari.jpg',
   true, true, ARRAY['chicken','slow-cooked','gravy','breakfast']),

  -- ── 7. Crispy Samosas ────────────────────────────────────────────────────
  (v_uid,
   'Crispy Potato Samosas',
   'Golden, flaky pastry triangles filled with spiced potato and peas. The ultimate halal snack for any gathering.',
   '[{"step":1,"text":"Boil potatoes until tender. Peel and roughly mash, leaving some chunks for texture."},
     {"step":2,"text":"Heat oil and fry cumin seeds until they sizzle. Add peas, green chilli, amchur and garam masala. Stir 2 minutes."},
     {"step":3,"text":"Combine the spice mixture with the mashed potato. Season well and leave to cool completely."},
     {"step":4,"text":"Cut spring roll or samosa pastry into strips. Fold one end into a cone, fill with potato mixture, then fold and seal with a flour-water paste."},
     {"step":5,"text":"Deep-fry in oil at 170°C for 4–5 minutes, turning until uniformly golden."},
     {"step":6,"text":"Drain on paper towels. Serve hot with mint chutney and tamarind chutney."}]'::jsonb,
   '[{"name":"medium potatoes","amount":"4","unit":""},
     {"name":"frozen peas","amount":"100","unit":"g"},
     {"name":"samosa or spring roll pastry sheets","amount":"12","unit":""},
     {"name":"cumin seeds","amount":"1","unit":"tsp"},
     {"name":"garam masala","amount":"1","unit":"tsp"},
     {"name":"amchur (dried mango powder)","amount":"0.5","unit":"tsp"},
     {"name":"green chilli (finely chopped)","amount":"1","unit":""},
     {"name":"oil for deep frying","amount":"1","unit":"litre"}]'::jsonb,
   'South Asian', 'medium', 55, 6,
   '/images/Recipes/crispy-potato-samosas.jpg',
   true, true, ARRAY['snack','fried','pastry','vegetarian']),

  -- ── 8. Tandoori Chicken ──────────────────────────────────────────────────
  (v_uid,
   'Tandoori Chicken',
   'Vibrant, charred chicken marinated in yogurt and aromatic spices. Perfectly smoky from the grill, served with naan and a squeeze of lemon.',
   '[{"step":1,"text":"Score chicken legs deeply with a sharp knife so the marinade can penetrate."},
     {"step":2,"text":"Combine yogurt, tandoori masala, lemon juice, ginger-garlic paste, Kashmiri chilli and oil. Mix well."},
     {"step":3,"text":"Coat the chicken thoroughly in the marinade. Refrigerate for at least 4 hours (overnight is best)."},
     {"step":4,"text":"Preheat grill or oven to 220°C. Place chicken on a rack and cook for 25–30 minutes, turning halfway."},
     {"step":5,"text":"For extra char, finish under the grill for 3–4 minutes on each side."},
     {"step":6,"text":"Serve with sliced onions, lemon wedges, mint chutney and fresh naan."}]'::jsonb,
   '[{"name":"chicken legs","amount":"4","unit":""},
     {"name":"full-fat yogurt","amount":"200","unit":"g"},
     {"name":"tandoori masala","amount":"3","unit":"tbsp"},
     {"name":"Kashmiri red chilli powder","amount":"1","unit":"tsp"},
     {"name":"ginger-garlic paste","amount":"2","unit":"tbsp"},
     {"name":"lemon juice","amount":"2","unit":"tbsp"},
     {"name":"vegetable oil","amount":"2","unit":"tbsp"},
     {"name":"salt","amount":"1.5","unit":"tsp"}]'::jsonb,
   'South Asian', 'easy', 45, 4,
   '/images/Recipes/tandoori-chicken.png',
   true, true, ARRAY['chicken','grilled','tandoori','marinade']),

  -- ── 9. Chicken Shawarma ──────────────────────────────────────────────────
  (v_uid,
   'Chicken Shawarma',
   'Middle Eastern street-food at its finest — spiced chicken thighs grilled to perfection, wrapped in warm flatbread with garlic sauce and pickles.',
   '[{"step":1,"text":"Mix shawarma spice blend (cumin, coriander, turmeric, cinnamon, allspice, black pepper) with lemon juice, olive oil, yogurt and garlic. Add chicken thighs and marinate for 2 hours."},
     {"step":2,"text":"Cook chicken in a hot griddle pan or under a grill for 6–7 minutes per side until cooked through and charred at the edges."},
     {"step":3,"text":"Rest 5 minutes, then slice thinly across the grain."},
     {"step":4,"text":"Make garlic sauce: blend garlic, lemon juice, salt and mayonnaise or whisk with tahini until smooth."},
     {"step":5,"text":"Warm flatbreads. Spread garlic sauce, lay sliced chicken, add tomatoes, pickles and fresh parsley."},
     {"step":6,"text":"Roll tightly, cut in half and serve immediately."}]'::jsonb,
   '[{"name":"boneless chicken thighs","amount":"700","unit":"g"},
     {"name":"shawarma spice blend","amount":"2.5","unit":"tbsp"},
     {"name":"full-fat yogurt","amount":"100","unit":"ml"},
     {"name":"lemon juice","amount":"3","unit":"tbsp"},
     {"name":"garlic cloves","amount":"4","unit":""},
     {"name":"flatbreads (khubz)","amount":"4","unit":""},
     {"name":"pickled turnips","amount":"80","unit":"g"},
     {"name":"tahini","amount":"2","unit":"tbsp"}]'::jsonb,
   'Middle Eastern', 'medium', 35, 4,
   '/images/Recipes/chicken-shawarma.jpg',
   true, true, ARRAY['wrap','street food','chicken','grilled']),

  -- ── 10. Classic Hummus ───────────────────────────────────────────────────
  (v_uid,
   'Classic Hummus',
   'Velvety, restaurant-quality hummus made with just six ingredients. Smooth, nutty, and ready in 15 minutes.',
   '[{"step":1,"text":"If using dried chickpeas, soak overnight and boil until very soft. If using tinned, drain and reserve the liquid."},
     {"step":2,"text":"While warm, blend chickpeas in a food processor for 1 full minute until they form a smooth paste."},
     {"step":3,"text":"Add tahini, lemon juice, crushed garlic and salt. Blend for another minute."},
     {"step":4,"text":"With the motor running, drizzle in ice-cold water, a tablespoon at a time, until the hummus is very light and fluffy."},
     {"step":5,"text":"Taste and adjust lemon and salt. Transfer to a wide bowl."},
     {"step":6,"text":"Make a well in the centre, drizzle with olive oil, sprinkle paprika and optional pine nuts. Serve with warm pitta."}]'::jsonb,
   '[{"name":"cooked chickpeas","amount":"400","unit":"g"},
     {"name":"good-quality tahini","amount":"80","unit":"ml"},
     {"name":"lemon juice","amount":"3","unit":"tbsp"},
     {"name":"garlic clove","amount":"1","unit":""},
     {"name":"ice-cold water","amount":"4","unit":"tbsp"},
     {"name":"extra-virgin olive oil","amount":"3","unit":"tbsp"},
     {"name":"smoked paprika","amount":"0.5","unit":"tsp"},
     {"name":"salt","amount":"1","unit":"tsp"}]'::jsonb,
   'Middle Eastern', 'easy', 15, 6,
   '/images/Recipes/classic-hummus.jpg',
   true, true, ARRAY['dip','chickpeas','vegan','quick']),

  -- ── 11. Crispy Falafel ───────────────────────────────────────────────────
  (v_uid,
   'Crispy Falafel',
   'Golden, herb-packed chickpea fritters with a crunchy shell and fluffy interior. A Middle Eastern staple — great in wraps or on their own.',
   '[{"step":1,"text":"Soak dried chickpeas in cold water for 12 hours. Drain. Do NOT use tinned chickpeas — they are too soft."},
     {"step":2,"text":"Blend chickpeas with onion, garlic, parsley, coriander, cumin, coriander seeds, baking powder and salt until finely ground but not smooth."},
     {"step":3,"text":"Refrigerate the mixture for 30 minutes — it helps them hold shape."},
     {"step":4,"text":"Roll into 3 cm balls, flatten slightly, and coat in sesame seeds if desired."},
     {"step":5,"text":"Heat oil to 175°C. Fry in batches for 3–4 minutes until deep golden all over."},
     {"step":6,"text":"Drain and serve immediately in warm pitta with tahini sauce, cucumber and fresh tomato."}]'::jsonb,
   '[{"name":"dried chickpeas","amount":"250","unit":"g"},
     {"name":"small white onion","amount":"1","unit":""},
     {"name":"garlic cloves","amount":"3","unit":""},
     {"name":"fresh parsley","amount":"40","unit":"g"},
     {"name":"fresh coriander","amount":"40","unit":"g"},
     {"name":"ground cumin","amount":"1.5","unit":"tsp"},
     {"name":"baking powder","amount":"1","unit":"tsp"},
     {"name":"sesame seeds","amount":"2","unit":"tbsp"}]'::jsonb,
   'Middle Eastern', 'medium', 30, 4,
   '/images/Recipes/crispy-falafel.jpg',
   true, true, ARRAY['chickpeas','fried','vegan','street food']),

  -- ── 12. Lamb Mansaf ──────────────────────────────────────────────────────
  (v_uid,
   'Jordanian Lamb Mansaf',
   'The national dish of Jordan — a magnificent feast of slow-cooked lamb over saffron rice, drenched in tangy jameed yogurt sauce and showered with toasted nuts.',
   '[{"step":1,"text":"Dissolve jameed (or dried goat yogurt) in 1 litre warm water, whisking until smooth. Pass through a sieve."},
     {"step":2,"text":"In a large pot, brown lamb pieces in ghee with salt and whole spices. Add the jameed broth, bring to a boil, then simmer covered for 1.5 hours until lamb is very tender."},
     {"step":3,"text":"Cook basmati rice in the lamb broth until fluffy and separate."},
     {"step":4,"text":"Toast almonds and pine nuts in butter until golden."},
     {"step":5,"text":"Layer flatbread on a large tray, top with rice, then arrange lamb on top."},
     {"step":6,"text":"Pour warm jameed sauce generously over the entire dish. Garnish with toasted nuts and parsley. Serve immediately."}]'::jsonb,
   '[{"name":"bone-in lamb (shoulder, cubed)","amount":"1.2","unit":"kg"},
     {"name":"jameed or dried goat yogurt","amount":"250","unit":"g"},
     {"name":"basmati rice","amount":"400","unit":"g"},
     {"name":"ghee","amount":"3","unit":"tbsp"},
     {"name":"toasted pine nuts","amount":"50","unit":"g"},
     {"name":"toasted almonds","amount":"50","unit":"g"},
     {"name":"saffron","amount":"1","unit":"pinch"},
     {"name":"thin flatbread (markook)","amount":"2","unit":"sheets"}]'::jsonb,
   'Middle Eastern', 'hard', 120, 6,
   '/images/Recipes/jordanian-lamb-mansaf.jpg',
   true, true, ARRAY['lamb','Jordan','celebratory','yogurt']),

  -- ── 13. Saudi Kabsa ──────────────────────────────────────────────────────
  (v_uid,
   'Saudi Kabsa',
   'The pride of the Arabian Peninsula — fragrant spiced rice cooked with whole chicken, tomatoes and dried fruits, finished with fried onions and toasted nuts.',
   '[{"step":1,"text":"Heat ghee in a large pot. Fry onions until golden. Add whole spices (cinnamon, cardamom, cloves, bay leaf) and stir 1 minute."},
     {"step":2,"text":"Add chicken pieces and brown on all sides. Add ginger, garlic, kabsa spice blend and black lime (loomi). Stir 2 minutes."},
     {"step":3,"text":"Add tinned tomatoes and 800ml water. Bring to a boil, then simmer covered for 40 minutes."},
     {"step":4,"text":"Remove chicken. Strain and measure the broth. Add washed rice to the broth (1.5 cups broth per cup rice). Cook covered on low heat for 18 minutes."},
     {"step":5,"text":"Rest rice 10 minutes. Meanwhile, re-crisp the chicken under a hot grill for 5 minutes."},
     {"step":6,"text":"Serve rice topped with chicken, fried onions, raisins and toasted almonds."}]'::jsonb,
   '[{"name":"whole chicken (jointed)","amount":"1.5","unit":"kg"},
     {"name":"basmati rice","amount":"500","unit":"g"},
     {"name":"kabsa spice blend","amount":"2","unit":"tbsp"},
     {"name":"dried black lime (loomi)","amount":"2","unit":""},
     {"name":"tinned chopped tomatoes","amount":"400","unit":"g"},
     {"name":"onions","amount":"2","unit":"large"},
     {"name":"raisins","amount":"40","unit":"g"},
     {"name":"toasted almonds","amount":"50","unit":"g"}]'::jsonb,
   'Middle Eastern', 'medium', 80, 6,
   '/images/Recipes/saudi-kabsa.jpg',
   true, true, ARRAY['rice','Saudi','chicken','festive']),

  -- ── 14. Tabbouleh ────────────────────────────────────────────────────────
  (v_uid,
   'Lebanese Tabbouleh',
   'A bright, herb-forward salad with far more parsley than bulgur. Light, zesty and incredibly fresh — a staple of Lebanese mezze.',
   '[{"step":1,"text":"Rinse bulgur wheat. Cover with cold water and leave to soak for 20 minutes. Drain well and squeeze out excess moisture in a clean cloth."},
     {"step":2,"text":"Finely chop a huge bunch of flat-leaf parsley (including tender stems). Chop fresh mint leaves."},
     {"step":3,"text":"Dice tomatoes into small cubes. Thinly slice spring onions."},
     {"step":4,"text":"Combine bulgur, parsley, mint, tomatoes and spring onions in a large bowl."},
     {"step":5,"text":"Dress with lemon juice, olive oil, a pinch of allspice and salt. Toss gently."},
     {"step":6,"text":"Leave to rest 15 minutes so the bulgur absorbs the dressing. Taste and adjust before serving."}]'::jsonb,
   '[{"name":"fine bulgur wheat","amount":"60","unit":"g"},
     {"name":"flat-leaf parsley (2 large bunches)","amount":"200","unit":"g"},
     {"name":"fresh mint","amount":"30","unit":"g"},
     {"name":"ripe tomatoes","amount":"3","unit":"medium"},
     {"name":"spring onions","amount":"4","unit":""},
     {"name":"lemon juice","amount":"60","unit":"ml"},
     {"name":"extra-virgin olive oil","amount":"60","unit":"ml"},
     {"name":"ground allspice","amount":"0.25","unit":"tsp"}]'::jsonb,
   'Middle Eastern', 'easy', 20, 4,
   '/images/Recipes/lebanese-tabbouleh.jpg',
   true, true, ARRAY['salad','herbs','vegan','mezze']),

  -- ── 15. Baked Kibbeh ─────────────────────────────────────────────────────
  (v_uid,
   'Baked Kibbeh',
   'A Lebanese classic of two layers of spiced lamb-bulgur dough sandwiching a savoury pine nut filling — baked until golden and sliced into diamonds.',
   '[{"step":1,"text":"Soak fine bulgur for 20 minutes. Drain and squeeze dry. Combine with raw lamb mince, grated onion, allspice, cinnamon and salt. Knead well — this is the dough."},
     {"step":2,"text":"For the filling: fry onion until golden, add lamb mince and brown. Stir in allspice, cinnamon and pine nuts. Season and cool."},
     {"step":3,"text":"Preheat oven to 190°C. Oil a rectangular baking dish."},
     {"step":4,"text":"Press half the kibbeh dough into a smooth, even layer in the dish."},
     {"step":5,"text":"Spread the cooled filling over the dough. Cover with the remaining dough and press flat."},
     {"step":6,"text":"Score the top in a diamond pattern with a knife. Drizzle with olive oil. Bake 35–40 minutes until golden brown."},
     {"step":7,"text":"Rest 5 minutes. Cut along the scored lines and serve with yogurt and fresh salad."}]'::jsonb,
   '[{"name":"fine bulgur wheat","amount":"200","unit":"g"},
     {"name":"lean lamb mince","amount":"500","unit":"g"},
     {"name":"onion","amount":"2","unit":"medium"},
     {"name":"pine nuts","amount":"60","unit":"g"},
     {"name":"ground allspice","amount":"1.5","unit":"tsp"},
     {"name":"ground cinnamon","amount":"0.5","unit":"tsp"},
     {"name":"olive oil","amount":"4","unit":"tbsp"},
     {"name":"salt and black pepper","amount":"","unit":"to taste"}]'::jsonb,
   'Middle Eastern', 'medium', 60, 6,
   '/images/Recipes/baked-kibbeh.jpg',
   true, true, ARRAY['lamb','baked','Lebanese','mezze']),

  -- ── 16. Chicken Tagine ───────────────────────────────────────────────────
  (v_uid,
   'Moroccan Chicken Tagine',
   'Slow-braised chicken with preserved lemons, green olives, saffron and warming spices in a rich aromatic sauce. Best mopped up with crusty bread.',
   '[{"step":1,"text":"Heat olive oil in a tagine or heavy-based casserole. Brown chicken pieces on all sides. Set aside."},
     {"step":2,"text":"In the same pot, fry onions until soft. Add garlic, ginger, turmeric, cumin, coriander and saffron. Stir 2 minutes."},
     {"step":3,"text":"Return chicken to the pot. Add 200ml water or chicken stock."},
     {"step":4,"text":"Cut preserved lemon into wedges, scrape out the pulp and discard, then add the rind to the pot."},
     {"step":5,"text":"Add green olives. Cover tightly and cook on very low heat for 1 hour, turning chicken halfway."},
     {"step":6,"text":"Remove lid and simmer 10 minutes to reduce the sauce slightly."},
     {"step":7,"text":"Garnish with fresh coriander and serve with crusty bread or couscous."}]'::jsonb,
   '[{"name":"chicken thighs (bone-in)","amount":"1","unit":"kg"},
     {"name":"preserved lemons","amount":"2","unit":""},
     {"name":"green olives","amount":"100","unit":"g"},
     {"name":"onions (sliced)","amount":"2","unit":"large"},
     {"name":"saffron","amount":"1","unit":"pinch"},
     {"name":"ground ginger","amount":"1","unit":"tsp"},
     {"name":"ground turmeric","amount":"0.5","unit":"tsp"},
     {"name":"olive oil","amount":"3","unit":"tbsp"}]'::jsonb,
   'Moroccan', 'medium', 90, 4,
   '/images/Recipes/moroccan-chicken-tagine.jpg',
   true, true, ARRAY['tagine','Moroccan','slow-cooked','chicken']),

  -- ── 17. Harira Soup ──────────────────────────────────────────────────────
  (v_uid,
   'Harira Soup',
   'Morocco''s iconic hearty soup of lamb, chickpeas, lentils and tomatoes, thickened with a flour-tomato mixture. Traditionally served to break the Ramadan fast.',
   '[{"step":1,"text":"Brown small lamb pieces in a large pot with oil. Add onion, celery and fry until soft."},
     {"step":2,"text":"Stir in tomato paste, fresh tomatoes, saffron, turmeric, cinnamon, ginger, pepper and salt."},
     {"step":3,"text":"Add pre-soaked chickpeas, rinsed red lentils and 1.5 litres water. Bring to a boil, skim, then simmer 40 minutes."},
     {"step":4,"text":"Mix 2 tbsp flour with 4 tbsp tomato juice to form a smooth paste (tedouira). Stir into the soup."},
     {"step":5,"text":"Add vermicelli and cook 5 minutes. The soup will thicken considerably — adjust with water if needed."},
     {"step":6,"text":"Stir in lemon juice and fresh coriander. Serve with dates and lemon on the side."}]'::jsonb,
   '[{"name":"lamb (small cubes)","amount":"300","unit":"g"},
     {"name":"canned chickpeas","amount":"200","unit":"g"},
     {"name":"red lentils","amount":"100","unit":"g"},
     {"name":"ripe tomatoes","amount":"4","unit":""},
     {"name":"tomato paste","amount":"2","unit":"tbsp"},
     {"name":"celery stalks","amount":"2","unit":""},
     {"name":"vermicelli noodles","amount":"60","unit":"g"},
     {"name":"saffron and warming spices","amount":"","unit":"to taste"}]'::jsonb,
   'Moroccan', 'easy', 60, 6,
   '/images/Recipes/harira-soup.jpg',
   true, true, ARRAY['soup','Ramadan','lamb','lentils']),

  -- ── 18. Lamb Couscous ────────────────────────────────────────────────────
  (v_uid,
   'Moroccan Lamb Couscous',
   'Fluffy steamed couscous piled high with tender braised lamb and a rainbow of vegetables in saffron-spiced broth. A true communal feast.',
   '[{"step":1,"text":"Brown lamb in a couscoussier or large pot with olive oil. Add onion, ras el hanout, saffron, ginger, turmeric and cinnamon. Stir 2 minutes."},
     {"step":2,"text":"Cover with 1.5 litres water. Bring to boil, skim, then simmer covered for 1 hour."},
     {"step":3,"text":"Add carrots, turnips and courgettes to the broth. Continue simmering 30 minutes."},
     {"step":4,"text":"Meanwhile, place dry couscous in a bowl. Pour over 1 cup boiling water with a pinch of salt and 1 tbsp butter. Cover and steam 10 minutes. Fluff with a fork."},
     {"step":5,"text":"Drain chickpeas and stir into the stew for the last 10 minutes."},
     {"step":6,"text":"Pile couscous on a large platter, arrange vegetables and lamb on top. Ladle the broth over and serve with harissa on the side."}]'::jsonb,
   '[{"name":"bone-in lamb shoulder (cubed)","amount":"1","unit":"kg"},
     {"name":"couscous","amount":"400","unit":"g"},
     {"name":"ras el hanout","amount":"2","unit":"tbsp"},
     {"name":"cooked chickpeas","amount":"200","unit":"g"},
     {"name":"carrots","amount":"3","unit":""},
     {"name":"courgettes","amount":"2","unit":""},
     {"name":"saffron","amount":"1","unit":"pinch"},
     {"name":"harissa (to serve)","amount":"","unit":""}]'::jsonb,
   'Moroccan', 'medium', 110, 6,
   '/images/Recipes/moroccan-lamb-couscous.jpg',
   true, true, ARRAY['couscous','lamb','Moroccan','feast']),

  -- ── 19. Chicken Bastilla ─────────────────────────────────────────────────
  (v_uid,
   'Chicken Bastilla',
   'Morocco''s extraordinary sweet-savoury pie: crispy warqa pastry layered with spiced shredded chicken, a creamy egg filling and a crunchy almond layer dusted with icing sugar.',
   '[{"step":1,"text":"Simmer chicken with onion, saffron, ginger, cinnamon, coriander and parsley until cooked. Shred the meat and discard bones."},
     {"step":2,"text":"Reduce the cooking liquid to a few tablespoons. Beat eggs into the hot liquid, stirring constantly until just set. Remove from heat."},
     {"step":3,"text":"Toast almonds and blitz roughly with cinnamon and icing sugar."},
     {"step":4,"text":"Brush a 28 cm round pan with melted butter. Layer 4 sheets of warqa or filo pastry, buttering each."},
     {"step":5,"text":"Spread shredded chicken, then egg mixture, then almond mixture. Fold pastry edges over. Lay 4 more buttered sheets on top and tuck underneath."},
     {"step":6,"text":"Bake at 190°C for 25–30 minutes until golden and very crispy."},
     {"step":7,"text":"Dust generously with icing sugar and ground cinnamon. Serve immediately while hot and crisp."}]'::jsonb,
   '[{"name":"chicken (whole or pieces)","amount":"1.5","unit":"kg"},
     {"name":"warqa or filo pastry","amount":"8","unit":"sheets"},
     {"name":"whole almonds (blanched)","amount":"150","unit":"g"},
     {"name":"eggs","amount":"5","unit":""},
     {"name":"saffron","amount":"2","unit":"pinches"},
     {"name":"icing sugar","amount":"4","unit":"tbsp"},
     {"name":"ground cinnamon","amount":"1","unit":"tsp"},
     {"name":"unsalted butter","amount":"100","unit":"g"}]'::jsonb,
   'Moroccan', 'hard', 120, 6,
   '/images/Recipes/chicken-bastilla.jpg',
   true, false, ARRAY['pie','pastry','Moroccan','festive']),

  -- ── 20. Iskender Kebab ───────────────────────────────────────────────────
  (v_uid,
   'Iskender Kebab',
   'Turkey''s most famous kebab — thin slices of doner meat laid over cubes of pide bread, drenched in hot tomato sauce and sizzling brown butter, served with yogurt.',
   '[{"step":1,"text":"Mix lamb mince with grated onion, salt, cumin, coriander and black pepper. Knead well. Shape into thin oval patties or a loaf."},
     {"step":2,"text":"Grill on a hot griddle or cook in a dry pan for 3–4 minutes per side. Slice into thin strips."},
     {"step":3,"text":"Make tomato sauce: fry garlic in butter, add tinned tomatoes, simmer 15 minutes with salt and chilli flakes."},
     {"step":4,"text":"Toast pide or flatbread and cut into 3 cm cubes. Arrange in the base of warm serving plates."},
     {"step":5,"text":"Layer the sliced meat over the bread."},
     {"step":6,"text":"Spoon hot tomato sauce over everything. Heat butter until foaming and pour it over the top."},
     {"step":7,"text":"Add a generous dollop of cold yogurt on the side. Serve at once."}]'::jsonb,
   '[{"name":"lamb mince","amount":"600","unit":"g"},
     {"name":"pide or flatbread","amount":"2","unit":""},
     {"name":"unsalted butter","amount":"80","unit":"g"},
     {"name":"tinned chopped tomatoes","amount":"400","unit":"g"},
     {"name":"full-fat yogurt","amount":"200","unit":"g"},
     {"name":"garlic cloves","amount":"3","unit":""},
     {"name":"ground cumin","amount":"1","unit":"tsp"},
     {"name":"chilli flakes","amount":"0.5","unit":"tsp"}]'::jsonb,
   'Turkish', 'medium', 45, 4,
   '/images/Recipes/iskender-kebab.jpg',
   true, true, ARRAY['kebab','Turkish','lamb','bread']),

  -- ── 21. Lahmacun ─────────────────────────────────────────────────────────
  (v_uid,
   'Lahmacun',
   'Turkish flatbread pizza — paper-thin dough topped with a spiced minced lamb mixture and baked at high heat until crisp. Roll it up with fresh parsley and a squeeze of lemon.',
   '[{"step":1,"text":"Make dough: combine flour, yeast, salt, olive oil and warm water. Knead for 8 minutes until smooth. Rest 1 hour."},
     {"step":2,"text":"Blend lamb mince with onion, red pepper, tomato, parsley, paprika, cumin, chilli flakes and salt into a spreadable paste."},
     {"step":3,"text":"Preheat oven as high as it will go (250°C+) with a pizza stone or upturned baking tray inside."},
     {"step":4,"text":"Divide dough into 4 balls. Roll each as thin as possible (2mm) on a floured surface."},
     {"step":5,"text":"Spread a thin, even layer of the meat paste all the way to the edges."},
     {"step":6,"text":"Bake for 6–8 minutes until the edges are crisp and the meat is cooked."},
     {"step":7,"text":"Roll up immediately. Serve with fresh parsley, sliced onion and lemon wedges."}]'::jsonb,
   '[{"name":"plain flour","amount":"300","unit":"g"},
     {"name":"instant yeast","amount":"5","unit":"g"},
     {"name":"lamb mince","amount":"300","unit":"g"},
     {"name":"red pepper","amount":"1","unit":""},
     {"name":"onion","amount":"1","unit":"medium"},
     {"name":"tomato","amount":"1","unit":""},
     {"name":"paprika","amount":"1","unit":"tsp"},
     {"name":"flat-leaf parsley","amount":"30","unit":"g"}]'::jsonb,
   'Turkish', 'medium', 55, 4,
   '/images/Recipes/lahmacun.jpg',
   true, true, ARRAY['flatbread','Turkish','lamb','baked']),

  -- ── 22. Menemen ──────────────────────────────────────────────────────────
  (v_uid,
   'Menemen',
   'Turkey''s beloved breakfast scramble — silky eggs gently cooked into a chunky tomato and pepper sauce. Serve straight from the pan with crusty bread.',
   '[{"step":1,"text":"Heat olive oil in a wide, shallow pan. Fry diced green peppers and onion over medium heat for 5 minutes until soft."},
     {"step":2,"text":"Add diced ripe tomatoes. Season with salt, black pepper and a pinch of chilli flakes. Cook 10 minutes until tomatoes break down into a sauce."},
     {"step":3,"text":"Make wells in the sauce and crack in the eggs. Season each yolk with a little salt."},
     {"step":4,"text":"Cover the pan and cook on low heat for 2–3 minutes. The whites should set but the yolks stay slightly runny."},
     {"step":5,"text":"Remove from heat. Crumble feta over the top and scatter with fresh flat-leaf parsley."},
     {"step":6,"text":"Serve immediately in the pan with crusty bread for scooping."}]'::jsonb,
   '[{"name":"eggs","amount":"4","unit":""},
     {"name":"ripe tomatoes","amount":"3","unit":"large"},
     {"name":"green bell pepper","amount":"2","unit":""},
     {"name":"onion","amount":"1","unit":"small"},
     {"name":"olive oil","amount":"2","unit":"tbsp"},
     {"name":"feta cheese","amount":"60","unit":"g"},
     {"name":"chilli flakes","amount":"0.25","unit":"tsp"},
     {"name":"flat-leaf parsley","amount":"10","unit":"g"}]'::jsonb,
   'Turkish', 'easy', 20, 2,
   '/images/Recipes/menemen.jpg',
   true, true, ARRAY['breakfast','eggs','Turkish','quick']),

  -- ── 23. Jollof Rice ──────────────────────────────────────────────────────
  (v_uid,
   'West African Jollof Rice',
   'The legendary West African party rice — long-grain rice cooked in a bold tomato-pepper base until every grain is deeply flavoured and the bottom is smoky and slightly crispy.',
   '[{"step":1,"text":"Blend tomatoes, red peppers, onion and scotch bonnet (deseed for less heat) into a smooth purée."},
     {"step":2,"text":"Heat oil in a heavy pot and fry half a sliced onion until golden. Add tomato paste and cook 2 minutes."},
     {"step":3,"text":"Add the blended pepper mixture. Cook on medium-high heat, stirring often, for 20 minutes until the raw smell is gone and the sauce has darkened and thickened."},
     {"step":4,"text":"Pour in chicken stock, add thyme, bay leaves, curry powder and season well. Bring to a boil."},
     {"step":5,"text":"Stir in washed long-grain rice. Mix once, then reduce heat to very low. Cover tightly with foil then the lid."},
     {"step":6,"text":"Cook for 30 minutes without lifting the lid. Remove foil, stir gently from the bottom, re-cover and cook 10 more minutes until rice is tender."},
     {"step":7,"text":"Serve with fried plantain and grilled chicken."}]'::jsonb,
   '[{"name":"long-grain rice","amount":"500","unit":"g"},
     {"name":"ripe tomatoes","amount":"4","unit":"large"},
     {"name":"red bell peppers","amount":"2","unit":""},
     {"name":"scotch bonnet pepper","amount":"1","unit":""},
     {"name":"onions","amount":"2","unit":"medium"},
     {"name":"chicken stock","amount":"500","unit":"ml"},
     {"name":"tomato paste","amount":"2","unit":"tbsp"},
     {"name":"dried thyme","amount":"1","unit":"tsp"}]'::jsonb,
   'West African', 'medium', 65, 6,
   '/images/Recipes/west-african-jollof-rice.jpg',
   true, true, ARRAY['rice','West African','tomato','festive']),

  -- ── 24. Suya Skewers ─────────────────────────────────────────────────────
  (v_uid,
   'Nigerian Suya Skewers',
   'Nigeria''s favourite street-food — thin strips of beef threaded on skewers, coated in a spiced groundnut paste and grilled over an open flame until smoky and deeply caramelised.',
   '[{"step":1,"text":"Blend groundnut (peanut) powder, paprika, ginger, garlic, onion powder, cayenne, kuli kuli (if available) and salt into a dry rub."},
     {"step":2,"text":"Slice beef sirloin or rump against the grain into very thin strips (4–5mm). Thread several strips onto long skewers, keeping them flat."},
     {"step":3,"text":"Brush generously with oil, then coat all sides with the suya spice mix, pressing to adhere."},
     {"step":4,"text":"Grill over high heat (charcoal is best) for 3–4 minutes per side until charred and cooked through."},
     {"step":5,"text":"Rest 2 minutes. Serve on newspaper or a board with sliced raw onions, tomatoes and extra ground pepper."}]'::jsonb,
   '[{"name":"beef sirloin or rump","amount":"600","unit":"g"},
     {"name":"roasted groundnut (peanut) powder","amount":"100","unit":"g"},
     {"name":"paprika","amount":"1.5","unit":"tsp"},
     {"name":"ground ginger","amount":"1","unit":"tsp"},
     {"name":"garlic powder","amount":"0.5","unit":"tsp"},
     {"name":"cayenne pepper","amount":"0.5","unit":"tsp"},
     {"name":"onion powder","amount":"0.5","unit":"tsp"},
     {"name":"vegetable oil","amount":"3","unit":"tbsp"}]'::jsonb,
   'West African', 'easy', 25, 4,
   '/images/Recipes/nigerian-suya-skewers.jpg',
   true, true, ARRAY['beef','grilled','Nigerian','street food']),

  -- ── 25. Chermoula Grilled Fish ───────────────────────────────────────────
  (v_uid,
   'Chermoula Grilled Sea Bass',
   'Whole sea bass fillets marinated in chermoula — a fragrant North African herb and spice paste — then grilled until the skin is crispy. Fast, healthy and full of flavour.',
   '[{"step":1,"text":"Make chermoula: blend together fresh coriander, flat-leaf parsley, garlic, lemon juice, olive oil, cumin, paprika, preserved lemon rind (optional) and salt until smooth."},
     {"step":2,"text":"Score the skin of sea bass fillets a few times with a sharp knife. Rub chermoula all over the fish, including into the cuts. Marinate 30 minutes."},
     {"step":3,"text":"Heat a grill pan or outdoor grill to high. Brush with oil."},
     {"step":4,"text":"Place fish skin-side down and press firmly. Grill 4 minutes without moving until the skin is crisp and releases naturally."},
     {"step":5,"text":"Flip gently and cook 2–3 more minutes until flesh is opaque and flakes easily."},
     {"step":6,"text":"Serve immediately with lemon wedges, warm bread and a simple green salad or roasted vegetables."}]'::jsonb,
   '[{"name":"sea bass fillets","amount":"4","unit":""},
     {"name":"fresh coriander","amount":"40","unit":"g"},
     {"name":"flat-leaf parsley","amount":"30","unit":"g"},
     {"name":"garlic cloves","amount":"3","unit":""},
     {"name":"lemon","amount":"2","unit":""},
     {"name":"ground cumin","amount":"1","unit":"tsp"},
     {"name":"smoked paprika","amount":"1","unit":"tsp"},
     {"name":"extra-virgin olive oil","amount":"5","unit":"tbsp"}]'::jsonb,
   'Mediterranean', 'easy', 25, 4,
   '/images/Recipes/chermoula-grilled-sea-bass.jpg',
   true, true, ARRAY['fish','grilled','Moroccan','healthy'])

  ON CONFLICT DO NOTHING;

END $$;
